apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.kafka.statefulset.name }}
spec:
  serviceName: {{ .Values.kafka.statefulset.serviceName }}
  replicas: {{ .Values.kafka.statefulset.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.kafka.statefulset.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.kafka.statefulset.name }}
    spec:
      containers:
        - name: {{ .Values.kafka.statefulset.name }}
          image: "{{ .Values.kafka.statefulset.image }}:{{ .Values.kafka.statefulset.tag }}"
          args:
            - redpanda
            - start
            - --overprovisioned
            - --smp
            - "1"
            - --memory
            - "512M"
            - --reserve-memory
            - "0M"
            - --node-id
            - "0"
            - --check=false
            - --kafka-addr
            - "PLAINTEXT://0.0.0.0:9092"
            - --advertise-kafka-addr
            - "PLAINTEXT://kafka:9092"
            - --rpc-addr
            - "0.0.0.0:33145"
            - --advertise-rpc-addr
            - "kafka:33145"
          ports:
            - containerPort: {{ .Values.kafka.statefulset.containerPort }}
          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/redpanda/data
          readinessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 10
            periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi