apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.statefulset.name }}
spec:
  selector:
    app: {{ .Values.mongo.statefulset.name }}
  ports:
    - port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}